export const PROFILE_ERROR = "PROFILE_ERROR";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_IMAGE_SUCCESS = "PROFILE_IMAGE_SUCCESS";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_SESSION_LIST_LOADING = "PROFILE_SESSION_LIST_LOADING";
export const PROFILE_SESSION_LIST_SUCCESS = "PROFILE_SESSION_LIST_SUCCESS";
export const PROFILE_SESSION_LIST_ERROR = "PROFILE_SESSION_LIST_ERROR";


export const profileActionCreators = {
  profileIsLoading: isLoading => ({
    type: PROFILE_LOADING,
    isLoading: isLoading
  })
};
